name: Rebuild Image

on:
  # schedule:
  #   - cron: "0 0 * * *" # run daily
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        # if: steps.check_version.outputs.should_build == 'true'
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: signal24/mysql-router-s3:latest
          build-args: |
            ORIGIN_HASH=${{ steps.check_version.outputs.ORIGIN_HASH }}
